export const REQUEST_FAILED = 'Request failed';
export const GET_TYPES = 'Get Types';
export const GET_ITEMS = 'Get Recipes';
export const ORDER_BY = 'Order By';
export const FILTER_BY = 'Filter By';
export const GET_ITEM_BY_ID = 'Get item by ID';
export const SET_ITEM = 'Set item';
export const CLEAR_ITEM = 'Clear item by ID';
export const CLEAR_ERROR = 'Clear Error';